### ISSUE TITLE
Anmelden

### ISSUE THREAD

**Issue by gastendonk** [SoltauFintel/fander#1]
Es sollte möglich sein Login+Passwort an die REST API zu senden. Diese sollte dann ggf. den geheimen User Token generieren. Es wird dann der User Token geliefert. Alle folgenden Aufrufe erfolgen dann mit dem User Token.

Es sollte auch ein Logout geben. Dieser zerstört dann den User Token.

**Comment by SoltauFintel** [comment]
in 1.02.2 eingebaut
